// 规则包需要可kmodule.xml文件下kbase的packages属性保持，否则读取不到
package demo1
// 导入类
import com.laher.study.drools.entity.Customer
// 得到礼物函数
function String getGift(String userName,String giftName){
    return "客户叫做："+userName+"，得到礼品："+giftName;
}
// 礼物类型
declare Gift
    name :String
end
// 规则名称，不可重复
rule 小额消费
when
    // 条件：存在Customer对象（Customer不为空）
    // 条件：消费金额大于0并且小于200
    c:Customer(money>0 && money<200)
then
    // 满足条件执行操作
    System.out.println("客户叫做："+c.name+"，消费金额："+c.money);
end
rule 大额消费
when
    // 条件：存在Customer对象（Customer不为空）
    // 条件：消费金额大于等于200
    c:Customer(money>=200)
then
    // 满足条件执行操作
    System.out.println("客户叫做："+c.name+"，大额消费："+c.money);
    Gift gift = new Gift();
    gift.setName("优质用户礼物");
    insert(gift);
end
rule 未消费
when
    // 条件：存在Customer对象（Customer不为空）
    // 条件：消费金额为0
    c:Customer(money==0)
then
    // 满足条件执行操作
    System.out.println("客户叫做："+c.name+"未消费");
end
rule 发送礼物
when
    c:Customer(money>=200)
    g:Gift()
then
    System.out.println(getGift(c.name,g.getName()));
end